#!/usr/bin/env python3
"""Autogenerate CATALOG.md by scanning a target's `*-bloque*.md` blocks (Research-SDD).

Generic: detects any prefix (`<something>-bloqueN.md`), extracts the block number
from the file name and the title from the first `# Block N — ...` line. Copy it to
`<TARGET>/tools/`. Do NOT edit CATALOG.md by hand; regenerate with:
  python3 tools/gen-catalog.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BLOCK_RE = re.compile(r"^(?P<prefix>.+)-(?:block|bloque)(?P<num>\d+)(?:-[\w-]+)?\.md$")
TITLE_RE = re.compile(r"^#\s*(?:Block|Bloque)\s*\d+\s*[—-]\s*(.+?)\s*$")


def block_title(path: Path) -> str:
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("# "):
                m = TITLE_RE.match(line.rstrip("\n"))
                return m.group(1) if m else line[2:].strip()
    return "(untitled)"


def main() -> int:
    blocks: list[tuple[int, str, str]] = []
    subject = ""
    for path in ROOT.glob("*.md"):
        m = BLOCK_RE.match(path.name)
        if not m:
            continue
        subject = subject or m.group("prefix")
        blocks.append((int(m.group("num")), path.name, block_title(path)))

    blocks.sort(key=lambda b: b[0])

    lines = [
        "<!-- AUTOGENERATED by tools/gen-catalog.py — DO NOT EDIT BY HAND. "
        "Regenerate: python3 tools/gen-catalog.py -->",
        "",
        f"# Block catalog — {subject or '<subject>'}",
        "",
        f"Total: **{len(blocks)} blocks**",
        "",
        "| Block | File | Title |",
        "|-------|------|-------|",
    ]
    for num, fname, title in blocks:
        lines.append(f"| {num} | [{fname}]({fname}) | {title} |")
    lines.append("")

    (ROOT / "CATALOG.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"CATALOG.md regenerated: {len(blocks)} blocks.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
